-- Migration: 045_seed_agent_run_config.sql

INSERT INTO agent_run_config (audit_type, stale_after_days, default_model, notes) VALUES
('full', 30, 'kimi', 'On-demand/monthly'),
('technical', 30, 'deepseek-v4-flash', 'Structured checks — cheap model candidate'),
('content', 30, 'kimi', 'Judgment-heavy — keep on Kimi'),
('content_brief', 9999, 'kimi', 'On-demand, tied to content calendar'),
('schema', 9999, 'deepseek-v4-flash', 'Structured extraction — cheap model candidate'),
('sitemap', 9999, 'deepseek-v4-flash', 'Structured — cheap model candidate'),
('images', 30, 'deepseek-v4-flash', 'Structured checks — cheap model candidate'),
('geo', 30, 'kimi', 'Nuanced citability judgment'),
('local', 7, 'kimi', 'Weekly'),
('maps', 7, 'kimi', 'Weekly, needs DataForSEO'),
('hreflang', 9999, 'deepseek-v4-flash', 'Structured validation'),
('google', 7, 'kimi', 'Weekly'),
('backlinks', 7, 'kimi', 'Weekly, feeds outreach — needs judgment on link quality'),
('cluster', 30, 'kimi', 'Monthly'),
('sxo', 30, 'kimi', 'Monthly, judgment-heavy'),
('drift', 7, 'kimi', 'Automatic weekly, not manually triggered'),
('ecommerce', 30, 'kimi', 'Conditional'),
('flow', 90, 'kimi', 'Quarterly strategy'),
('competitor_pages', 9999, 'kimi', 'On-demand'),
('plan', 9999, 'kimi', 'Once per onboarding'),
('programmatic', 9999, 'kimi', 'On-demand, conditional'),
('dataforseo', 9999, 'kimi', 'Budget-gated, on-demand'),
('image_gen', 9999, 'kimi', 'On-demand creative');
